var DATA = {
  "Pink": "pink_discog.json", 
  "The Black Eyed Peas": "the_black_eyed_peas_discog.json", 
  "Jordan Smith": "jordan_smith_discog.json", 
  "Tracy Byrd": "tracy_byrd_discog.json", 
  "Tim McGraw": "tim_mcgraw_discog.json", 
  "Nicki Minaj": "nicki_minaj_discog.json", 
  "Richard Marx": "richard_marx_discog.json", 
  "Beyonce": "beyonce_discog.json", 
  "Brantley Gilbert": "brantley_gilbert_discog.json", 
  "Jack Johnson": "jack_johnson_discog.json", 
  "Avicii": "avicii_discog.json", 
  "Kelly Clarkson": "kelly_clarkson_discog.json", 
  "The Weeknd": "the_weeknd_discog.json", 
  "Alicia Keys": "alicia_keys_discog.json", 
  "Phil Collins": "phil_collins_discog.json", 
  "Gavin DeGraw": "gavin_degraw_discog.json", 
  "Rihanna": "rihanna_discog.json", 
  "Natalie Cole": "natalie_cole_discog.json", 
  "The Offspring": "the_offspring_discog.json", 
  "Paul McCartney": "paul_mccartney_discog.json", 
  "Brett Eldredge": "brett_eldredge_discog.json", 
  "Aaliyah": "aaliyah_discog.json", 
  "INXS": "inxs_discog.json", 
  "Jesse McCartney": "jesse_mccartney_discog.json", 
  "Reba McEntire": "reba_mcentire_discog.json", 
  "Mario": "mario_discog.json", 
  "Cole Swindell": "cole_swindell_discog.json", 
  "Kenny Loggins": "kenny_loggins_discog.json", 
  "Destiny's Child": "destinys_child_discog.json", 
  "James Blunt": "james_blunt_discog.json", 
  "Eminem": "eminem_discog.json", 
  "Billy Joel": "billy_joel_discog.json", 
  "Brandy": "brandy_discog.json", 
  "Justin Bieber": "justin_bieber_discog.json", 
  "Rodney Atkins": "rodney_atkins_discog.json", 
  "10,000 Maniacs": "10,000_maniacs_discog.json", 
  "Backstreet Boys": "backstreet_boys_discog.json", 
  "REO Speedwagon": "reo_speedwagon_discog.json", 
  "Dustin Lynch": "dustin_lynch_discog.json", 
  "Kings Of Leon": "kings_of_leon_discog.json", 
  "Darius Rucker": "darius_rucker_discog.json", 
  "Breaking Benjamin": "breaking_benjamin_discog.json", 
  "Fall Out Boy": "fall_out_boy_discog.json", 
  "Daughtry": "daughtry_discog.json", 
  "Heart": "heart_discog.json", 
  "Rod Stewart": "rod_stewart_discog.json", 
  "Chris Young": "chris_young_discog.json", 
  "The Pointer Sisters": "the_pointer_sisters_discog.json", 
  "Three Days Grace": "three_days_grace_discog.json", 
  "Chris Brown": "chris_brown_discog.json", 
  "P!nk": "p!nk_discog.json", 
  "Eli Young Band": "eli_young_band_discog.json", 
  "Tina Turner": "tina_turner_discog.json", 
  "Ariana Grande": "ariana_grande_discog.json", 
  "Justin Moore": "justin_moore_discog.json", 
  "Jessica Simpson": "jessica_simpson_discog.json", 
  "Nelly": "nelly_discog.json", 
  "Glenn Frey": "glenn_frey_discog.json", 
  "Avril Lavigne": "avril_lavigne_discog.json", 
  "ZZ Top": "zz_top_discog.json", 
  "Dru Hill": "dru_hill_discog.json", 
  "Paramore": "paramore_discog.json", 
  "Flo Rida": "flo_rida_discog.json", 
  "Guns N  Roses": "guns_n__roses_discog.json", 
  "Eric Church": "eric_church_discog.json", 
  "Creed": "creed_discog.json", 
  "Ludacris": "ludacris_discog.json", 
  "Katy Perry": "katy_perry_discog.json", 
  "Colbie Caillat": "colbie_caillat_discog.json", 
  "Andy Grammer": "andy_grammer_discog.json", 
  "Monica": "monica_discog.json", 
  "Easton Corbin": "easton_corbin_discog.json", 
  "Gary Allan": "gary_allan_discog.json", 
  "Ke$ha": "ke$ha_discog.json", 
  "Pat Benatar": "pat_benatar_discog.json", 
  "Shakira": "shakira_discog.json", 
  "Lifehouse": "lifehouse_discog.json", 
  "Lil Wayne": "lil_wayne_discog.json", 
  "Glee Cast": "glee_cast_discog.json", 
  "Miranda Lambert": "miranda_lambert_discog.json", 
  "Young Thug": "young_thug_discog.json", 
  "Busta Rhymes": "busta_rhymes_discog.json", 
  "Gloria Estefan": "gloria_estefan_discog.json", 
  "Seal": "seal_discog.json", 
  "Amy Grant": "amy_grant_discog.json", 
  "Boyz II Men": "boyz_ii_men_discog.json", 
  "John Mellencamp": "john_mellencamp_discog.json", 
  "50 Cent": "50_cent_discog.json", 
  "Red Hot Chili Peppers": "red_hot_chili_peppers_discog.json", 
  "Zac Brown Band": "zac_brown_band_discog.json", 
  "Jo Dee Messina": "jo_dee_messina_discog.json", 
  "Ginuwine": "ginuwine_discog.json", 
  "Joe Nichols": "joe_nichols_discog.json", 
  "Sting": "sting_discog.json", 
  "Panic! At The Disco": "panic!_at_the_disco_discog.json", 
  "Paula Abdul": "paula_abdul_discog.json", 
  "Sheryl Crow": "sheryl_crow_discog.json", 
  "Simple Plan": "simple_plan_discog.json", 
  "Michelle Branch": "michelle_branch_discog.json", 
  "T.I.": "t.i._discog.json", 
  "Bryan Adams": "bryan_adams_discog.json", 
  "Bonnie Raitt": "bonnie_raitt_discog.json", 
  "twenty one pilots": "twenty_one_pilots_discog.json", 
  "Janet": "janet_discog.json", 
  "Phil Vassar": "phil_vassar_discog.json", 
  "Train": "train_discog.json", 
  "The Cure": "the_cure_discog.json", 
  "matchbox twenty": "matchbox_twenty_discog.json", 
  "Shawn Mendes": "shawn_mendes_discog.json", 
  "Kylie Minogue": "kylie_minogue_discog.json", 
  "Shinedown": "shinedown_discog.json", 
  "Aerosmith": "aerosmith_discog.json", 
  "Daryl Hall  John Oates": "daryl_hall__john_oates_discog.json", 
  "Journey": "journey_discog.json", 
  "Rascal Flatts": "rascal_flatts_discog.json", 
  "Ne-Yo": "ne-yo_discog.json", 
  "No Doubt": "no_doubt_discog.json", 
  "Hannah Montana": "hannah_montana_discog.json", 
  "Usher": "usher_discog.json", 
  "OneRepublic": "onerepublic_discog.json", 
  "Robin Thicke": "robin_thicke_discog.json", 
  "Metallica": "metallica_discog.json", 
  "Roxette": "roxette_discog.json", 
  "Hilary Duff": "hilary_duff_discog.json", 
  "Motley Crue": "motley_crue_discog.json", 
  "Duran Duran": "duran_duran_discog.json", 
  "Incubus": "incubus_discog.json", 
  "Ellie Goulding": "ellie_goulding_discog.json", 
  "Faith Hill": "faith_hill_discog.json", 
  "3OH!3": "3oh!3_discog.json", 
  "Jewel": "jewel_discog.json", 
  "Meghan Trainor": "meghan_trainor_discog.json", 
  "Air Supply": "air_supply_discog.json", 
  "Jerrod Niemann": "jerrod_niemann_discog.json", 
  "Whitney Houston": "whitney_houston_discog.json", 
  "Ed Sheeran": "ed_sheeran_discog.json", 
  "Madonna": "madonna_discog.json", 
  "Christina Aguilera": "christina_aguilera_discog.json", 
  "R. Kelly": "r._kelly_discog.json", 
  "En Vogue": "en_vogue_discog.json", 
  "Elton John": "elton_john_discog.json", 
  "Enrique Iglesias": "enrique_iglesias_discog.json", 
  "Puddle Of Mudd": "puddle_of_mudd_discog.json", 
  "Jason Derulo": "jason_derulo_discog.json", 
  "Kim Carnes": "kim_carnes_discog.json", 
  "Wiz Khalifa": "wiz_khalifa_discog.json", 
  "Migos": "migos_discog.json", 
  "Prince": "prince_discog.json", 
  "Sam Smith": "sam_smith_discog.json", 
  "The Band Perry": "the_band_perry_discog.json", 
  "Disturbed": "disturbed_discog.json", 
  "Gwen Stefani": "gwen_stefani_discog.json", 
  "John Michael Montgomery": "john_michael_montgomery_discog.json", 
  "Ciara": "ciara_discog.json", 
  "The Police": "the_police_discog.json", 
  "Thompson Square": "thompson_square_discog.json", 
  "Staind": "staind_discog.json", 
  "Xscape": "xscape_discog.json", 
  "UB40": "ub40_discog.json", 
  "Sawyer Fredericks": "sawyer_fredericks_discog.json", 
  "Meek Mill": "meek_mill_discog.json", 
  "Lonestar": "lonestar_discog.json", 
  "Lenny Kravitz": "lenny_kravitz_discog.json", 
  "Kellie Pickler": "kellie_pickler_discog.json", 
  "Depeche Mode": "depeche_mode_discog.json", 
  "David Cook": "david_cook_discog.json", 
  "Pitbull": "pitbull_discog.json", 
  "Fergie": "fergie_discog.json", 
  "Papa Roach": "papa_roach_discog.json", 
  "Poison": "poison_discog.json", 
  "Luther Vandross": "luther_vandross_discog.json", 
  "Bruce Springsteen": "bruce_springsteen_discog.json", 
  "Drake & Future": "drake_&_future_discog.json", 
  "Justin Timberlake": "justin_timberlake_discog.json", 
  "Nickelback": "nickelback_discog.json", 
  "Cassadee Pope": "cassadee_pope_discog.json", 
  "Billy Currington": "billy_currington_discog.json", 
  "Sam Hunt": "sam_hunt_discog.json", 
  "Genesis": "genesis_discog.json", 
  "Kendrick Lamar": "kendrick_lamar_discog.json", 
  "Trey Songz": "trey_songz_discog.json", 
  "Trace Adkins": "trace_adkins_discog.json", 
  "Hunter Hayes": "hunter_hayes_discog.json", 
  "System Of A Down": "system_of_a_down_discog.json", 
  "Martina McBride": "martina_mcbride_discog.json", 
  "Ricky Martin": "ricky_martin_discog.json", 
  "Chris Cagle": "chris_cagle_discog.json", 
  "Green Day": "green_day_discog.json", 
  "The Killers": "the_killers_discog.json", 
  "Akon": "akon_discog.json", 
  "Sara Evans": "sara_evans_discog.json", 
  "Lee Brice": "lee_brice_discog.json", 
  "M.C. Hammer": "m.c._hammer_discog.json", 
  "Billy Squier": "billy_squier_discog.json", 
  "Alan Jackson": "alan_jackson_discog.json", 
  "Michael Jackson": "michael_jackson_discog.json", 
  "Big & Rich": "big_&_rich_discog.json", 
  "2Pac": "2pac_discog.json", 
  "Little Big Town": "little_big_town_discog.json", 
  "3 Doors Down": "3_doors_down_discog.json", 
  "David Bowie": "david_bowie_discog.json", 
  "George Strait": "george_strait_discog.json", 
  "Craig Morgan": "craig_morgan_discog.json", 
  "Fetty Wap": "fetty_wap_discog.json", 
  "Shania Twain": "shania_twain_discog.json", 
  "Survivor": "survivor_discog.json", 
  "Dan Fogelberg": "dan_fogelberg_discog.json", 
  "Dave Matthews Band": "dave_matthews_band_discog.json", 
  "TLC": "tlc_discog.json", 
  "Selena Gomez & The Scene": "selena_gomez_&_the_scene_discog.json", 
  "Frank Ocean": "frank_ocean_discog.json", 
  "Florida Georgia Line": "florida_georgia_line_discog.json", 
  "Dierks Bentley": "dierks_bentley_discog.json", 
  "Fantasia": "fantasia_discog.json", 
  "Lady Antebellum": "lady_antebellum_discog.json", 
  "New Edition": "new_edition_discog.json", 
  "Mariah Carey": "mariah_carey_discog.json", 
  "Kanye West": "kanye_west_discog.json", 
  "Rae Sremmurd": "rae_sremmurd_discog.json", 
  "Rob Thomas": "rob_thomas_discog.json", 
  "Kenny Chesney": "kenny_chesney_discog.json", 
  "J. Cole": "j._cole_discog.json", 
  "Eddie Money": "eddie_money_discog.json", 
  "The Alan Parsons Project": "the_alan_parsons_project_discog.json", 
  "Spice Girls": "spice_girls_discog.json", 
  "The Cars": "the_cars_discog.json", 
  "Steve Winwood": "steve_winwood_discog.json", 
  "My Chemical Romance": "my_chemical_romance_discog.json", 
  "Adele": "adele_discog.json", 
  "Kris Allen": "kris_allen_discog.json", 
  "George Michael": "george_michael_discog.json", 
  "Thomas Rhett": "thomas_rhett_discog.json", 
  "Lorde": "lorde_discog.json", 
  "Joe Diffie": "joe_diffie_discog.json", 
  "Janet Jackson": "janet_jackson_discog.json", 
  "R.E.M.": "r.e.m._discog.json", 
  "Goo Goo Dolls": "goo_goo_dolls_discog.json", 
  "Natasha Bedingfield": "natasha_bedingfield_discog.json", 
  "Nelly Furtado": "nelly_furtado_discog.json", 
  "Mac Miller": "mac_miller_discog.json", 
  "Van Halen": "van_halen_discog.json", 
  "Tyrese": "tyrese_discog.json", 
  "Maroon5": "maroon5_discog.json", 
  "Vanessa Williams": "vanessa_williams_discog.json", 
  "Sugarland": "sugarland_discog.json", 
  "Britney Spears": "britney_spears_discog.json", 
  "Pearl Jam": "pearl_jam_discog.json", 
  "Nas": "nas_discog.json", 
  "Cyndi Lauper": "cyndi_lauper_discog.json", 
  "Coldplay": "coldplay_discog.json", 
  "Lee Ann Womack": "lee_ann_womack_discog.json", 
  "Miguel": "miguel_discog.json", 
  "The Fray": "the_fray_discog.json", 
  "Luke Bryan": "luke_bryan_discog.json", 
  "Taylor Swift": "taylor_swift_discog.json", 
  "Keyshia Cole": "keyshia_cole_discog.json", 
  "Celine Dion": "celine_dion_discog.json", 
  "Clay Walker": "clay_walker_discog.json", 
  "LeAnn Rimes": "leann_rimes_discog.json", 
  "Sarah McLachlan": "sarah_mclachlan_discog.json", 
  "Jonas Brothers": "jonas_brothers_discog.json", 
  "Lionel Richie": "lionel_richie_discog.json", 
  "Pet Shop Boys": "pet_shop_boys_discog.json", 
  "Jordin Sparks": "jordin_sparks_discog.json", 
  "Bruno Mars": "bruno_mars_discog.json", 
  "Imagine Dragons": "imagine_dragons_discog.json", 
  "Terri Clark": "terri_clark_discog.json", 
  "Keith Urban": "keith_urban_discog.json", 
  "Blake Shelton": "blake_shelton_discog.json", 
  "Drake Featuring Lil Wayne": "drake_featuring_lil_wayne_discog.json", 
  "Demi Lovato": "demi_lovato_discog.json", 
  "John Mayer": "john_mayer_discog.json", 
  "Sean Paul": "sean_paul_discog.json", 
  "Miley Cyrus": "miley_cyrus_discog.json", 
  "Danielle Bradbery": "danielle_bradbery_discog.json", 
  "Fleetwood Mac": "fleetwood_mac_discog.json", 
  "Dixie Chicks": "dixie_chicks_discog.json", 
  "Randy Houser": "randy_houser_discog.json", 
  "Jennifer Lopez": "jennifer_lopez_discog.json", 
  "5 Seconds Of Summer": "5_seconds_of_summer_discog.json", 
  "U2": "u2_discog.json", 
  "Lana Del Rey": "lana_del_rey_discog.json", 
  "Maroon 5": "maroon_5_discog.json", 
  "Sean Kingston": "sean_kingston_discog.json", 
  "Robert Palmer": "robert_palmer_discog.json", 
  "Foo Fighters": "foo_fighters_discog.json", 
  "Loverboy": "loverboy_discog.json", 
  "Montgomery Gentry": "montgomery_gentry_discog.json", 
  "Big Sean": "big_sean_discog.json", 
  "Avant": "avant_discog.json", 
  "Foreigner": "foreigner_discog.json", 
  "Josh Turner": "josh_turner_discog.json", 
  "Linkin Park": "linkin_park_discog.json", 
  "Lady Gaga": "lady_gaga_discog.json", 
  "Andy Griggs": "andy_griggs_discog.json", 
  "Future": "future_discog.json", 
  "Drake": "drake_discog.json", 
  "Def Leppard": "def_leppard_discog.json", 
  "Jake Owen": "jake_owen_discog.json", 
  "Musiq Soulchild": "musiq_soulchild_discog.json", 
  "OutKast": "outkast_discog.json", 
  "Sheena Easton": "sheena_easton_discog.json", 
  "Leona Lewis": "leona_lewis_discog.json", 
  "Audioslave": "audioslave_discog.json", 
  "Carrie Underwood": "carrie_underwood_discog.json", 
  "Rick Springfield": "rick_springfield_discog.json", 
  "Maxwell": "maxwell_discog.json", 
  "Michael Buble": "michael_buble_discog.json", 
  "Seether": "seether_discog.json", 
  "Brad Paisley": "brad_paisley_discog.json", 
  "Ashanti": "ashanti_discog.json", 
  "Jason Aldean": "jason_aldean_discog.json", 
  "One Direction": "one_direction_discog.json", 
  "Kenny Rogers": "kenny_rogers_discog.json", 
  "Night Ranger": "night_ranger_discog.json", 
  "Darryl Worley": "darryl_worley_discog.json", 
  "Selena Gomez": "selena_gomez_discog.json", 
  "Bon Jovi": "bon_jovi_discog.json", 
  "Toby Keith": "toby_keith_discog.json", 
  "Jay-Z": "jay-z_discog.json", 
  "Mary J. Blige": "mary_j._blige_discog.json", 
  "Adam Lambert": "adam_lambert_discog.json"
};
export default DATA;