var DATA = {
  "Michael Bolton": "michael_bolton_discog.json", 
  "Commodores": "commodores_discog.json", 
  "Beyonce": "beyonce_discog.json", 
  "Avicii": "avicii_discog.json", 
  "The Weeknd": "the_weeknd_discog.json", 
  "New Edition": "new_edition_discog.json", 
  "Reba McEntire": "reba_mcentire_discog.json", 
  "Sam Cooke": "sam_cooke_discog.json", 
  "James Blunt": "james_blunt_discog.json", 
  "Eminem": "eminem_discog.json", 
  "Rodney Atkins": "rodney_atkins_discog.json", 
  "Darius Rucker": "darius_rucker_discog.json", 
  "Daughtry": "daughtry_discog.json", 
  "Toto": "toto_discog.json", 
  "Three Days Grace": "three_days_grace_discog.json", 
  "The Beatles": "the_beatles_discog.json", 
  "Al Green": "al_green_discog.json", 
  "Don Henley": "don_henley_discog.json", 
  "Glenn Frey": "glenn_frey_discog.json", 
  "Rob Thomas": "rob_thomas_discog.json", 
  "Paramore": "paramore_discog.json", 
  "Guns N  Roses": "guns_n__roses_discog.json", 
  "Gary Allan": "gary_allan_discog.json", 
  "Kenny Chesney": "kenny_chesney_discog.json", 
  "John Waite": "john_waite_discog.json", 
  "Lana Del Rey": "lana_del_rey_discog.json", 
  "Trisha Yearwood": "trisha_yearwood_discog.json", 
  "Busta Rhymes": "busta_rhymes_discog.json", 
  "Boyz II Men": "boyz_ii_men_discog.json", 
  "John Mellencamp": "john_mellencamp_discog.json", 
  "50 Cent": "50_cent_discog.json", 
  "Red Hot Chili Peppers": "red_hot_chili_peppers_discog.json", 
  "Paula Abdul": "paula_abdul_discog.json", 
  "Roy Orbison": "roy_orbison_discog.json", 
  "Simple Plan": "simple_plan_discog.json", 
  "5 Seconds Of Summer": "5_seconds_of_summer_discog.json", 
  "Janet": "janet_discog.json", 
  "Train": "train_discog.json", 
  "The Cure": "the_cure_discog.json", 
  "The Alan Parsons Project": "the_alan_parsons_project_discog.json", 
  "Daryl Hall  John Oates": "daryl_hall__john_oates_discog.json", 
  "America": "america_discog.json", 
  "Metallica": "metallica_discog.json", 
  "Roxette": "roxette_discog.json", 
  "Pet Shop Boys": "pet_shop_boys_discog.json", 
  "Thomas Rhett": "thomas_rhett_discog.json", 
  "Meghan Trainor": "meghan_trainor_discog.json", 
  "Wilson Pickett": "wilson_pickett_discog.json", 
  "Disturbed": "disturbed_discog.json", 
  "Pitbull": "pitbull_discog.json", 
  "Michael Jackson": "michael_jackson_discog.json", 
  "Nat King Cole": "nat_king_cole_discog.json", 
  "Jerry Butler": "jerry_butler_discog.json", 
  "Queen": "queen_discog.json", 
  "B.B. King": "b.b._king_discog.json", 
  "Sara Evans": "sara_evans_discog.json", 
  "The Band Perry": "the_band_perry_discog.json", 
  "John Michael Montgomery": "john_michael_montgomery_discog.json", 
  "Ciara": "ciara_discog.json", 
  "Culture Club": "culture_club_discog.json", 
  "UB40": "ub40_discog.json", 
  "Sawyer Fredericks": "sawyer_fredericks_discog.json", 
  "Glen Campbell": "glen_campbell_discog.json", 
  "Kellie Pickler": "kellie_pickler_discog.json", 
  "Randy Houser": "randy_houser_discog.json", 
  "Annie Lennox": "annie_lennox_discog.json", 
  "Diana Ross": "diana_ross_discog.json", 
  "Drake & Future": "drake_&_future_discog.json", 
  "Justin Timberlake": "justin_timberlake_discog.json", 
  "Sam Hunt": "sam_hunt_discog.json", 
  "Whitney Houston": "whitney_houston_discog.json", 
  "Ricky Martin": "ricky_martin_discog.json", 
  "Akon": "akon_discog.json", 
  "Lee Brice": "lee_brice_discog.json", 
  "M.C. Hammer": "m.c._hammer_discog.json", 
  "Little Big Town": "little_big_town_discog.json", 
  "Connie Francis": "connie_francis_discog.json", 
  "Jackson 5": "jackson_5_discog.json", 
  "Craig Morgan": "craig_morgan_discog.json", 
  "Shania Twain": "shania_twain_discog.json", 
  "Foo Fighters": "foo_fighters_discog.json", 
  "Marvin Gaye": "marvin_gaye_discog.json", 
  "The Doobie Brothers": "the_doobie_brothers_discog.json", 
  "Ludacris": "ludacris_discog.json", 
  "Kim Carnes": "kim_carnes_discog.json", 
  "Carly Simon": "carly_simon_discog.json", 
  "Kris Allen": "kris_allen_discog.json", 
  "N Sync": "n_sync_discog.json", 
  "Bad Company": "bad_company_discog.json", 
  "Bob Seger": "bob_seger_discog.json", 
  "Sugarland": "sugarland_discog.json", 
  "The Police": "the_police_discog.json", 
  "Coldplay": "coldplay_discog.json", 
  "Lee Ann Womack": "lee_ann_womack_discog.json", 
  "Luke Bryan": "luke_bryan_discog.json", 
  "Taylor Swift": "taylor_swift_discog.json", 
  "Keith Urban": "keith_urban_discog.json", 
  "Aaliyah": "aaliyah_discog.json", 
  "Mac Miller": "mac_miller_discog.json", 
  "Etta James": "etta_james_discog.json", 
  "Nelly Furtado": "nelly_furtado_discog.json", 
  "Johnny Mathis": "johnny_mathis_discog.json", 
  "Avant": "avant_discog.json", 
  "Jake Owen": "jake_owen_discog.json", 
  "Dusty Springfield": "dusty_springfield_discog.json", 
  "James Brown": "james_brown_discog.json", 
  "Maxwell": "maxwell_discog.json", 
  "One Direction": "one_direction_discog.json", 
  "Seal": "seal_discog.json", 
  "Selena Gomez": "selena_gomez_discog.json", 
  "Michelle Branch": "michelle_branch_discog.json", 
  "The Black Eyed Peas": "the_black_eyed_peas_discog.json", 
  "Dionne Warwick": "dionne_warwick_discog.json", 
  "Ariana Grande": "ariana_grande_discog.json", 
  "Tim McGraw": "tim_mcgraw_discog.json", 
  "Jon Secada": "jon_secada_discog.json", 
  "Brantley Gilbert": "brantley_gilbert_discog.json", 
  "Rihanna": "rihanna_discog.json", 
  "Elvis Presley": "elvis_presley_discog.json", 
  "The Offspring": "the_offspring_discog.json", 
  "Brett Eldredge": "brett_eldredge_discog.json", 
  "Night Ranger": "night_ranger_discog.json", 
  "INXS": "inxs_discog.json", 
  "The Impressions": "the_impressions_discog.json", 
  "Sade": "sade_discog.json", 
  "Depeche Mode": "depeche_mode_discog.json", 
  "Beck": "beck_discog.json", 
  "Green Day": "green_day_discog.json", 
  "Bette Midler": "bette_midler_discog.json", 
  "Electric Light Orchestra": "electric_light_orchestra_discog.json", 
  "Kings Of Leon": "kings_of_leon_discog.json", 
  "Breaking Benjamin": "breaking_benjamin_discog.json", 
  "Barbra Streisand": "barbra_streisand_discog.json", 
  "Bob Dylan": "bob_dylan_discog.json", 
  "The Everly Brothers": "the_everly_brothers_discog.json", 
  "Janet Jackson": "janet_jackson_discog.json", 
  "Eli Young Band": "eli_young_band_discog.json", 
  "Tina Turner": "tina_turner_discog.json", 
  "The Dave Clark Five": "the_dave_clark_five_discog.json", 
  "Avril Lavigne": "avril_lavigne_discog.json", 
  "Dru Hill": "dru_hill_discog.json", 
  "Eric Church": "eric_church_discog.json", 
  "Four Tops": "four_tops_discog.json", 
  "Sting": "sting_discog.json", 
  "The Fray": "the_fray_discog.json", 
  "Andy Grammer": "andy_grammer_discog.json", 
  "Easton Corbin": "easton_corbin_discog.json", 
  "Shakira": "shakira_discog.json", 
  "Lifehouse": "lifehouse_discog.json", 
  "Glee Cast": "glee_cast_discog.json", 
  "Panic! At The Disco": "panic!_at_the_disco_discog.json", 
  "Jim Reeves": "jim_reeves_discog.json", 
  "Bobby Darin": "bobby_darin_discog.json", 
  "Anita Baker": "anita_baker_discog.json", 
  "Nelly": "nelly_discog.json", 
  "Journey": "journey_discog.json", 
  "Joe": "joe_discog.json", 
  "Hannah Montana": "hannah_montana_discog.json", 
  "Hilary Duff": "hilary_duff_discog.json", 
  "Johnny Cash": "johnny_cash_discog.json", 
  "The Moody Blues": "the_moody_blues_discog.json", 
  "Ellie Goulding": "ellie_goulding_discog.json", 
  "Howard Jones": "howard_jones_discog.json", 
  "Jerrod Niemann": "jerrod_niemann_discog.json", 
  "Miguel": "miguel_discog.json", 
  "The Smashing Pumpkins": "the_smashing_pumpkins_discog.json", 
  "George Strait": "george_strait_discog.json", 
  "Enrique Iglesias": "enrique_iglesias_discog.json", 
  "R.E.M.": "r.e.m._discog.json", 
  "Gwen Stefani": "gwen_stefani_discog.json", 
  "Marty Robbins": "marty_robbins_discog.json", 
  "Xscape": "xscape_discog.json", 
  "David Cook": "david_cook_discog.json", 
  "Toni Braxton": "toni_braxton_discog.json", 
  "Weird Al Yankovic": "weird_al_yankovic_discog.json", 
  "Santana": "santana_discog.json", 
  "Sarah McLachlan": "sarah_mclachlan_discog.json", 
  "Warrant": "warrant_discog.json", 
  "Genesis": "genesis_discog.json", 
  "John Denver": "john_denver_discog.json", 
  "Aretha Franklin": "aretha_franklin_discog.json", 
  "Pretenders": "pretenders_discog.json", 
  "Andy Williams": "andy_williams_discog.json", 
  "Chris Cagle": "chris_cagle_discog.json", 
  "The Killers": "the_killers_discog.json", 
  "Elton John": "elton_john_discog.json", 
  "Petula Clark": "petula_clark_discog.json", 
  "Alan Jackson": "alan_jackson_discog.json", 
  "Big & Rich": "big_&_rich_discog.json", 
  "David Bowie": "david_bowie_discog.json", 
  "Fetty Wap": "fetty_wap_discog.json", 
  "Tracy Byrd": "tracy_byrd_discog.json", 
  "TLC": "tlc_discog.json", 
  "Linda Ronstadt": "linda_ronstadt_discog.json", 
  "Jagged Edge": "jagged_edge_discog.json", 
  "Florida Georgia Line": "florida_georgia_line_discog.json", 
  "Zac Brown Band": "zac_brown_band_discog.json", 
  "Bobby Vinton": "bobby_vinton_discog.json", 
  "Kanye West": "kanye_west_discog.json", 
  "J. Cole": "j._cole_discog.json", 
  "Eddie Money": "eddie_money_discog.json", 
  "The Temptations": "the_temptations_discog.json", 
  "Perry Como": "perry_como_discog.json", 
  "Adele": "adele_discog.json", 
  "The 5th Dimension": "the_5th_dimension_discog.json", 
  "George Michael": "george_michael_discog.json", 
  "twenty one pilots": "twenty_one_pilots_discog.json", 
  "Madonna": "madonna_discog.json", 
  "James Brown And The Famous Flames": "james_brown_and_the_famous_flames_discog.json", 
  "Lesley Gore": "lesley_gore_discog.json", 
  "Loverboy": "loverboy_discog.json", 
  "Stevie Nicks": "stevie_nicks_discog.json", 
  "Chicago": "chicago_discog.json", 
  "Britney Spears": "britney_spears_discog.json", 
  "Cyndi Lauper": "cyndi_lauper_discog.json", 
  "Alice Cooper": "alice_cooper_discog.json", 
  "Keyshia Cole": "keyshia_cole_discog.json", 
  "Gladys Knight And The Pips": "gladys_knight_and_the_pips_discog.json", 
  "Imagine Dragons": "imagine_dragons_discog.json", 
  "Terri Clark": "terri_clark_discog.json", 
  "Natalie Cole": "natalie_cole_discog.json", 
  "Drake Featuring Lil Wayne": "drake_featuring_lil_wayne_discog.json", 
  "The Isley Brothers": "the_isley_brothers_discog.json", 
  "Kiss": "kiss_discog.json", 
  "Johnny Tillotson": "johnny_tillotson_discog.json", 
  "Shawn Mendes": "shawn_mendes_discog.json", 
  "Anne Murray": "anne_murray_discog.json", 
  "Andy Griggs": "andy_griggs_discog.json", 
  "Seether": "seether_discog.json", 
  "Melissa Etheridge": "melissa_etheridge_discog.json", 
  "Olivia Newton-John": "olivia_newton-john_discog.json", 
  "Tyrese": "tyrese_discog.json", 
  "Brad Paisley": "brad_paisley_discog.json", 
  "Ashanti": "ashanti_discog.json", 
  "Big Sean": "big_sean_discog.json", 
  "Bon Jovi": "bon_jovi_discog.json", 
  "Adam Lambert": "adam_lambert_discog.json", 
  "Nicki Minaj": "nicki_minaj_discog.json", 
  "Kelly Clarkson": "kelly_clarkson_discog.json", 
  "Flo Rida": "flo_rida_discog.json", 
  "Jordan Smith": "jordan_smith_discog.json", 
  "Ke$ha": "ke$ha_discog.json", 
  "Phil Collins": "phil_collins_discog.json", 
  "Young Thug": "young_thug_discog.json", 
  "Jesse McCartney": "jesse_mccartney_discog.json", 
  "Cole Swindell": "cole_swindell_discog.json", 
  "10,000 Maniacs": "10,000_maniacs_discog.json", 
  "Backstreet Boys": "backstreet_boys_discog.json", 
  "Dustin Lynch": "dustin_lynch_discog.json", 
  "Fall Out Boy": "fall_out_boy_discog.json", 
  "OutKast": "outkast_discog.json", 
  "Rod Stewart": "rod_stewart_discog.json", 
  "Fats Domino": "fats_domino_discog.json", 
  "Fergie": "fergie_discog.json", 
  "Kenny Rogers": "kenny_rogers_discog.json", 
  "Justin Moore": "justin_moore_discog.json", 
  "The Beach Boys": "the_beach_boys_discog.json", 
  "ZZ Top": "zz_top_discog.json", 
  "Jody Watley": "jody_watley_discog.json", 
  "Color Me Badd": "color_me_badd_discog.json", 
  "Colbie Caillat": "colbie_caillat_discog.json", 
  "Stevie B": "stevie_b_discog.json", 
  "Pat Benatar": "pat_benatar_discog.json", 
  "Miranda Lambert": "miranda_lambert_discog.json", 
  "Juice Newton": "juice_newton_discog.json", 
  "Katy Perry": "katy_perry_discog.json", 
  "Jo Dee Messina": "jo_dee_messina_discog.json", 
  "Laura Branigan": "laura_branigan_discog.json", 
  "Sheryl Crow": "sheryl_crow_discog.json", 
  "Rick Springfield": "rick_springfield_discog.json", 
  "Neil Diamond": "neil_diamond_discog.json", 
  "Dolly Parton": "dolly_parton_discog.json", 
  "My Chemical Romance": "my_chemical_romance_discog.json", 
  "Aerosmith": "aerosmith_discog.json", 
  "Usher": "usher_discog.json", 
  "Motley Crue": "motley_crue_discog.json", 
  "Faith Hill": "faith_hill_discog.json", 
  "3OH!3": "3oh!3_discog.json", 
  "System Of A Down": "system_of_a_down_discog.json", 
  "Christina Aguilera": "christina_aguilera_discog.json", 
  "T.I.": "t.i._discog.json", 
  "Jefferson Starship": "jefferson_starship_discog.json", 
  "R. Kelly": "r._kelly_discog.json", 
  "En Vogue": "en_vogue_discog.json", 
  "Ne-Yo": "ne-yo_discog.json", 
  "Puddle Of Mudd": "puddle_of_mudd_discog.json", 
  "Jason Derulo": "jason_derulo_discog.json", 
  "Wiz Khalifa": "wiz_khalifa_discog.json", 
  "John Mayer": "john_mayer_discog.json", 
  "Yes": "yes_discog.json", 
  "Bee Gees": "bee_gees_discog.json", 
  "Billy Joel": "billy_joel_discog.json", 
  "Luther Vandross": "luther_vandross_discog.json", 
  "Bruce Springsteen": "bruce_springsteen_discog.json", 
  "Robert Palmer": "robert_palmer_discog.json", 
  "Earth, Wind & Fire": "earth,_wind_&_fire_discog.json", 
  "Billy Currington": "billy_currington_discog.json", 
  "Kendrick Lamar": "kendrick_lamar_discog.json", 
  "Nancy Sinatra": "nancy_sinatra_discog.json", 
  "The Hollies": "the_hollies_discog.json", 
  "Ray Charles": "ray_charles_discog.json", 
  "The Monkees": "the_monkees_discog.json", 
  "Babyface": "babyface_discog.json", 
  "The Guess Who": "the_guess_who_discog.json", 
  "Neil Sedaka": "neil_sedaka_discog.json", 
  "Three Dog Night": "three_dog_night_discog.json", 
  "Barry Manilow": "barry_manilow_discog.json", 
  "Dave Matthews Band": "dave_matthews_band_discog.json", 
  "Donovan": "donovan_discog.json", 
  "Frank Ocean": "frank_ocean_discog.json", 
  "Dierks Bentley": "dierks_bentley_discog.json", 
  "The Pointer Sisters": "the_pointer_sisters_discog.json", 
  "Mariah Carey": "mariah_carey_discog.json", 
  "Rae Sremmurd": "rae_sremmurd_discog.json", 
  "Steve Winwood": "steve_winwood_discog.json", 
  "Incubus": "incubus_discog.json", 
  "Eurythmics": "eurythmics_discog.json", 
  "Van Halen": "van_halen_discog.json", 
  "Maroon5": "maroon5_discog.json", 
  "Frank Sinatra": "frank_sinatra_discog.json", 
  "Nas": "nas_discog.json", 
  "Celine Dion": "celine_dion_discog.json", 
  "Jonas Brothers": "jonas_brothers_discog.json", 
  "Survivor": "survivor_discog.json", 
  "Darryl Worley": "darryl_worley_discog.json", 
  "Brenda Lee": "brenda_lee_discog.json", 
  "Demi Lovato": "demi_lovato_discog.json", 
  "Spice Girls": "spice_girls_discog.json", 
  "Miley Cyrus": "miley_cyrus_discog.json", 
  "Dixie Chicks": "dixie_chicks_discog.json", 
  "LeAnn Rimes": "leann_rimes_discog.json", 
  "Goo Goo Dolls": "goo_goo_dolls_discog.json", 
  "Jennifer Lopez": "jennifer_lopez_discog.json", 
  "Paul Anka": "paul_anka_discog.json", 
  "Josh Turner": "josh_turner_discog.json", 
  "Linkin Park": "linkin_park_discog.json", 
  "Drake": "drake_discog.json", 
  "Dean Martin": "dean_martin_discog.json", 
  "Thompson Square": "thompson_square_discog.json", 
  "Leona Lewis": "leona_lewis_discog.json", 
  "Selena Gomez & The Scene": "selena_gomez_&_the_scene_discog.json", 
  "The Kinks": "the_kinks_discog.json", 
  "Collective Soul": "collective_soul_discog.json", 
  "Michael Buble": "michael_buble_discog.json", 
  "Jason Aldean": "jason_aldean_discog.json", 
  "Kylie Minogue": "kylie_minogue_discog.json", 
  "Bruno Mars": "bruno_mars_discog.json", 
  "Jordin Sparks": "jordin_sparks_discog.json", 
  "Toby Keith": "toby_keith_discog.json", 
  "Mary J. Blige": "mary_j._blige_discog.json", 
  "Pink": "pink_discog.json", 
  "Richard Marx": "richard_marx_discog.json", 
  "Jack Johnson": "jack_johnson_discog.json", 
  "Alicia Keys": "alicia_keys_discog.json", 
  "Gavin DeGraw": "gavin_degraw_discog.json", 
  "Paul McCartney": "paul_mccartney_discog.json", 
  "Ginuwine": "ginuwine_discog.json", 
  "Destiny's Child": "destinys_child_discog.json", 
  "Brandy": "brandy_discog.json", 
  "REO Speedwagon": "reo_speedwagon_discog.json", 
  "Sean Paul": "sean_paul_discog.json", 
  "Lady Antebellum": "lady_antebellum_discog.json", 
  "Chris Brown": "chris_brown_discog.json", 
  "Otis Redding": "otis_redding_discog.json", 
  "Danielle Bradbery": "danielle_bradbery_discog.json", 
  "Lionel Richie": "lionel_richie_discog.json", 
  "Chris Young": "chris_young_discog.json", 
  "98 Degrees": "98_degrees_discog.json", 
  "Papa Roach": "papa_roach_discog.json", 
  "The Supremes": "the_supremes_discog.json", 
  "Heart": "heart_discog.json", 
  "Jessica Simpson": "jessica_simpson_discog.json", 
  "The Rolling Stones": "the_rolling_stones_discog.json", 
  "Creed": "creed_discog.json", 
  "Gino Vannelli": "gino_vannelli_discog.json", 
  "Lorde": "lorde_discog.json", 
  "The Byrds": "the_byrds_discog.json", 
  "Prince": "prince_discog.json", 
  "Staind": "staind_discog.json", 
  "Lil Wayne": "lil_wayne_discog.json", 
  "Trey Songz": "trey_songz_discog.json", 
  "Gloria Estefan": "gloria_estefan_discog.json", 
  "Amy Grant": "amy_grant_discog.json", 
  "Hunter Hayes": "hunter_hayes_discog.json", 
  "U2": "u2_discog.json", 
  "Shinedown": "shinedown_discog.json", 
  "Joe Nichols": "joe_nichols_discog.json", 
  "Cassadee Pope": "cassadee_pope_discog.json", 
  "Bryan Adams": "bryan_adams_discog.json", 
  "Bonnie Raitt": "bonnie_raitt_discog.json", 
  "Phil Vassar": "phil_vassar_discog.json", 
  "matchbox twenty": "matchbox_twenty_discog.json", 
  "Thompson Twins": "thompson_twins_discog.json", 
  "Rascal Flatts": "rascal_flatts_discog.json", 
  "No Doubt": "no_doubt_discog.json", 
  "OneRepublic": "onerepublic_discog.json", 
  "Robin Thicke": "robin_thicke_discog.json", 
  "Duran Duran": "duran_duran_discog.json", 
  "Jewel": "jewel_discog.json", 
  "Air Supply": "air_supply_discog.json", 
  "Ed Sheeran": "ed_sheeran_discog.json", 
  "Tom Jones": "tom_jones_discog.json", 
  "Migos": "migos_discog.json", 
  "Sam Smith": "sam_smith_discog.json", 
  "Maroon 5": "maroon_5_discog.json", 
  "Trace Adkins": "trace_adkins_discog.json", 
  "Lonestar": "lonestar_discog.json", 
  "Lenny Kravitz": "lenny_kravitz_discog.json", 
  "The Who": "the_who_discog.json", 
  "Jodeci": "jodeci_discog.json", 
  "Kenny Loggins": "kenny_loggins_discog.json", 
  "Billy Ocean": "billy_ocean_discog.json", 
  "Poison": "poison_discog.json", 
  "Montgomery Gentry": "montgomery_gentry_discog.json", 
  "Billy Squier": "billy_squier_discog.json", 
  "Dr. Hook": "dr._hook_discog.json", 
  "Ace Of Base": "ace_of_base_discog.json", 
  "2Pac": "2pac_discog.json", 
  "3 Doors Down": "3_doors_down_discog.json", 
  "Foreigner": "foreigner_discog.json", 
  "Dan Fogelberg": "dan_fogelberg_discog.json", 
  "Chuck Berry": "chuck_berry_discog.json", 
  "The O'Jays": "the_ojays_discog.json", 
  "Cher": "cher_discog.json", 
  "Fantasia": "fantasia_discog.json", 
  "CeCe Peniston": "cece_peniston_discog.json", 
  "Stevie Wonder": "stevie_wonder_discog.json", 
  "The Drifters": "the_drifters_discog.json", 
  "Martina McBride": "martina_mcbride_discog.json", 
  "The Cars": "the_cars_discog.json", 
  "Joe Diffie": "joe_diffie_discog.json", 
  "Pearl Jam": "pearl_jam_discog.json", 
  "Natasha Bedingfield": "natasha_bedingfield_discog.json", 
  "Bruce Hornsby": "bruce_hornsby_discog.json", 
  "Vanessa Williams": "vanessa_williams_discog.json", 
  "Steely Dan": "steely_dan_discog.json", 
  "Donna Summer": "donna_summer_discog.json", 
  "Clay Walker": "clay_walker_discog.json", 
  "Monica": "monica_discog.json", 
  "Sheena Easton": "sheena_easton_discog.json", 
  "Herman's Hermits": "hermans_hermits_discog.json", 
  "Blake Shelton": "blake_shelton_discog.json", 
  "Mario": "mario_discog.json", 
  "Justin Bieber": "justin_bieber_discog.json", 
  "Nine Inch Nails": "nine_inch_nails_discog.json", 
  "Fleetwood Mac": "fleetwood_mac_discog.json", 
  "P!nk": "p!nk_discog.json", 
  "Sean Kingston": "sean_kingston_discog.json", 
  "ABBA": "abba_discog.json", 
  "Lady Gaga": "lady_gaga_discog.json", 
  "Nickelback": "nickelback_discog.json", 
  "Future": "future_discog.json", 
  "Meek Mill": "meek_mill_discog.json", 
  "Def Leppard": "def_leppard_discog.json", 
  "Musiq Soulchild": "musiq_soulchild_discog.json", 
  "Barenaked Ladies": "barenaked_ladies_discog.json", 
  "Audioslave": "audioslave_discog.json", 
  "Carrie Underwood": "carrie_underwood_discog.json", 
  "Styx": "styx_discog.json", 
  "Tears For Fears": "tears_for_fears_discog.json", 
  "Jay-Z": "jay-z_discog.json"
};
export default DATA;