var DATA = {
  "Michael Bolton": "michael_bolton_discog.json", 
  "Commodores": "commodores_discog.json", 
  "Beyonce": "beyonce_discog.json", 
  "The Weeknd": "the_weeknd_discog.json", 
  "New Edition": "new_edition_discog.json", 
  "Sam Cooke": "sam_cooke_discog.json", 
  "Eminem": "eminem_discog.json", 
  "Darius Rucker": "darius_rucker_discog.json", 
  "Daughtry": "daughtry_discog.json", 
  "Eddy Arnold": "eddy_arnold_discog.json", 
  "The Beatles": "the_beatles_discog.json", 
  "Al Green": "al_green_discog.json", 
  "Glenn Frey": "glenn_frey_discog.json", 
  "Guns N  Roses": "guns_n__roses_discog.json", 
  "Gary Allan": "gary_allan_discog.json", 
  "John Waite": "john_waite_discog.json", 
  "The Righteous Brothers": "the_righteous_brothers_discog.json", 
  "Boyz II Men": "boyz_ii_men_discog.json", 
  "John Mellencamp": "john_mellencamp_discog.json", 
  "Cheap Trick": "cheap_trick_discog.json", 
  "50 Cent": "50_cent_discog.json", 
  "Red Hot Chili Peppers": "red_hot_chili_peppers_discog.json", 
  "Paula Abdul": "paula_abdul_discog.json", 
  "Roy Orbison": "roy_orbison_discog.json", 
  "5 Seconds Of Summer": "5_seconds_of_summer_discog.json", 
  "The Cure": "the_cure_discog.json", 
  "The Alan Parsons Project": "the_alan_parsons_project_discog.json", 
  "Daryl Hall  John Oates": "daryl_hall__john_oates_discog.json", 
  "America": "america_discog.json", 
  "Metallica": "metallica_discog.json", 
  "Roxette": "roxette_discog.json", 
  "Pet Shop Boys": "pet_shop_boys_discog.json", 
  "The Turtles": "the_turtles_discog.json", 
  "Nickelback": "nickelback_discog.json", 
  "Wilson Pickett": "wilson_pickett_discog.json", 
  "Michael Jackson": "michael_jackson_discog.json", 
  "Nat King Cole": "nat_king_cole_discog.json", 
  "Jerry Butler": "jerry_butler_discog.json", 
  "Queen": "queen_discog.json", 
  "B.B. King": "b.b._king_discog.json", 
  "Sara Evans": "sara_evans_discog.json", 
  "Goo Goo Dolls": "goo_goo_dolls_discog.json", 
  "Al Martino": "al_martino_discog.json", 
  "Glen Campbell": "glen_campbell_discog.json", 
  "Diana Ross": "diana_ross_discog.json", 
  "The Spinners": "the_spinners_discog.json", 
  "Justin Timberlake": "justin_timberlake_discog.json", 
  "Cat Stevens": "cat_stevens_discog.json", 
  "Montgomery Gentry": "montgomery_gentry_discog.json", 
  "Connie Francis": "connie_francis_discog.json", 
  "George Strait": "george_strait_discog.json", 
  "Craig Morgan": "craig_morgan_discog.json", 
  "Shania Twain": "shania_twain_discog.json", 
  "Foo Fighters": "foo_fighters_discog.json", 
  "Marvin Gaye": "marvin_gaye_discog.json", 
  "The Doobie Brothers": "the_doobie_brothers_discog.json", 
  "Kenny Chesney": "kenny_chesney_discog.json", 
  "Kim Carnes": "kim_carnes_discog.json", 
  "Mariah Carey": "mariah_carey_discog.json", 
  "Carly Simon": "carly_simon_discog.json", 
  "Bad Company": "bad_company_discog.json", 
  "Bob Seger": "bob_seger_discog.json", 
  "Sugarland": "sugarland_discog.json", 
  "The Police": "the_police_discog.json", 
  "Coldplay": "coldplay_discog.json", 
  "Patsy Cline": "patsy_cline_discog.json", 
  "Jackson Browne": "jackson_browne_discog.json", 
  "Luke Bryan": "luke_bryan_discog.json", 
  "Taylor Swift": "taylor_swift_discog.json", 
  "Keith Urban": "keith_urban_discog.json", 
  "Aaliyah": "aaliyah_discog.json", 
  "Etta James": "etta_james_discog.json", 
  "Gordon Lightfoot": "gordon_lightfoot_discog.json", 
  "Loverboy": "loverboy_discog.json", 
  "Johnny Mathis": "johnny_mathis_discog.json", 
  "Ben E. King": "ben_e._king_discog.json", 
  "Carole King": "carole_king_discog.json", 
  "Jake Owen": "jake_owen_discog.json", 
  "Gene Pitney": "gene_pitney_discog.json", 
  "Dusty Springfield": "dusty_springfield_discog.json", 
  "James Brown": "james_brown_discog.json", 
  "One Direction": "one_direction_discog.json", 
  "Freddy Cannon": "freddy_cannon_discog.json", 
  "The Black Eyed Peas": "the_black_eyed_peas_discog.json", 
  "Dionne Warwick": "dionne_warwick_discog.json", 
  "Tim McGraw": "tim_mcgraw_discog.json", 
  "Rod Stewart": "rod_stewart_discog.json", 
  "Rihanna": "rihanna_discog.json", 
  "Elvis Presley": "elvis_presley_discog.json", 
  "Night Ranger": "night_ranger_discog.json", 
  "INXS": "inxs_discog.json", 
  "The Impressions": "the_impressions_discog.json", 
  "Depeche Mode": "depeche_mode_discog.json", 
  "Eddie Rabbitt": "eddie_rabbitt_discog.json", 
  "Bette Midler": "bette_midler_discog.json", 
  "Steppenwolf": "steppenwolf_discog.json", 
  "The Pointer Sisters": "the_pointer_sisters_discog.json", 
  "Barbra Streisand": "barbra_streisand_discog.json", 
  "Bob Dylan": "bob_dylan_discog.json", 
  "The Everly Brothers": "the_everly_brothers_discog.json", 
  "Chris Brown": "chris_brown_discog.json", 
  "Tina Turner": "tina_turner_discog.json", 
  "The Dave Clark Five": "the_dave_clark_five_discog.json", 
  "Avril Lavigne": "avril_lavigne_discog.json", 
  "Eric Church": "eric_church_discog.json", 
  "Bill Withers": "bill_withers_discog.json", 
  "Four Tops": "four_tops_discog.json", 
  "Sting": "sting_discog.json", 
  "Engelbert Humperdinck": "engelbert_humperdinck_discog.json", 
  "Glee Cast": "glee_cast_discog.json", 
  "The Marvelettes": "the_marvelettes_discog.json", 
  "Pearl Jam": "pearl_jam_discog.json", 
  "Jim Reeves": "jim_reeves_discog.json", 
  "Bobby Darin": "bobby_darin_discog.json", 
  "Anita Baker": "anita_baker_discog.json", 
  "Nelly": "nelly_discog.json", 
  "Journey": "journey_discog.json", 
  "Hannah Montana": "hannah_montana_discog.json", 
  "Johnny Cash": "johnny_cash_discog.json", 
  "The Moody Blues": "the_moody_blues_discog.json", 
  "Atlanta Rhythm Section": "atlanta_rhythm_section_discog.json", 
  "Howard Jones": "howard_jones_discog.json", 
  "Josh Turner": "josh_turner_discog.json", 
  "The Shirelles": "the_shirelles_discog.json", 
  "Brook Benton": "brook_benton_discog.json", 
  "R.E.M.": "r.e.m._discog.json", 
  "Del Shannon": "del_shannon_discog.json", 
  "Gwen Stefani": "gwen_stefani_discog.json", 
  "Marty Robbins": "marty_robbins_discog.json", 
  "David Cook": "david_cook_discog.json", 
  "Genesis": "genesis_discog.json", 
  "John Denver": "john_denver_discog.json", 
  "Aretha Franklin": "aretha_franklin_discog.json", 
  "Pretenders": "pretenders_discog.json", 
  "Andy Williams": "andy_williams_discog.json", 
  "The Killers": "the_killers_discog.json", 
  "Elton John": "elton_john_discog.json", 
  "Petula Clark": "petula_clark_discog.json", 
  "Alan Jackson": "alan_jackson_discog.json", 
  "David Bowie": "david_bowie_discog.json", 
  "TLC": "tlc_discog.json", 
  "Linda Ronstadt": "linda_ronstadt_discog.json", 
  "Florida Georgia Line": "florida_georgia_line_discog.json", 
  "Zac Brown Band": "zac_brown_band_discog.json", 
  "Bobby Vinton": "bobby_vinton_discog.json", 
  "Kanye West": "kanye_west_discog.json", 
  "J. Cole": "j._cole_discog.json", 
  "The Temptations": "the_temptations_discog.json", 
  "Perry Como": "perry_como_discog.json", 
  "Usher": "usher_discog.json", 
  "The 5th Dimension": "the_5th_dimension_discog.json", 
  "George Michael": "george_michael_discog.json", 
  "Madonna": "madonna_discog.json", 
  "James Brown And The Famous Flames": "james_brown_and_the_famous_flames_discog.json", 
  "Lesley Gore": "lesley_gore_discog.json", 
  "Stevie Nicks": "stevie_nicks_discog.json", 
  "Chicago": "chicago_discog.json", 
  "Britney Spears": "britney_spears_discog.json", 
  "Cyndi Lauper": "cyndi_lauper_discog.json", 
  "Alice Cooper": "alice_cooper_discog.json", 
  "Gladys Knight And The Pips": "gladys_knight_and_the_pips_discog.json", 
  "Chubby Checker": "chubby_checker_discog.json", 
  "The Lovin' Spoonful": "the_lovin_spoonful_discog.json", 
  "Little River Band": "little_river_band_discog.json", 
  "Natalie Cole": "natalie_cole_discog.json", 
  "Ginuwine": "ginuwine_discog.json", 
  "The Isley Brothers": "the_isley_brothers_discog.json", 
  "Kiss": "kiss_discog.json", 
  "Johnny Tillotson": "johnny_tillotson_discog.json", 
  "Anne Murray": "anne_murray_discog.json", 
  "Eric Clapton": "eric_clapton_discog.json", 
  "Rick Springfield": "rick_springfield_discog.json", 
  "Olivia Newton-John": "olivia_newton-john_discog.json", 
  "Brad Paisley": "brad_paisley_discog.json", 
  "Bon Jovi": "bon_jovi_discog.json", 
  "Adam Lambert": "adam_lambert_discog.json", 
  "Nicki Minaj": "nicki_minaj_discog.json", 
  "James Taylor": "james_taylor_discog.json", 
  "Kelly Clarkson": "kelly_clarkson_discog.json", 
  "Boz Scaggs": "boz_scaggs_discog.json", 
  "Ke$ha": "ke$ha_discog.json", 
  "Phil Collins": "phil_collins_discog.json", 
  "Tommy James And The Shondells": "tommy_james_and_the_shondells_discog.json", 
  "Leo Sayer": "leo_sayer_discog.json", 
  "George Harrison": "george_harrison_discog.json", 
  "Kansas": "kansas_discog.json", 
  "Backstreet Boys": "backstreet_boys_discog.json", 
  "Fall Out Boy": "fall_out_boy_discog.json", 
  "OutKast": "outkast_discog.json", 
  "Fats Domino": "fats_domino_discog.json", 
  "Kenny Rogers": "kenny_rogers_discog.json", 
  "The Beach Boys": "the_beach_boys_discog.json", 
  "ZZ Top": "zz_top_discog.json", 
  "Jody Watley": "jody_watley_discog.json", 
  "Colbie Caillat": "colbie_caillat_discog.json", 
  "Pat Benatar": "pat_benatar_discog.json", 
  "Melissa Manchester": "melissa_manchester_discog.json", 
  "Santana": "santana_discog.json", 
  "Juice Newton": "juice_newton_discog.json", 
  "Katy Perry": "katy_perry_discog.json", 
  "Laura Branigan": "laura_branigan_discog.json", 
  "Sheryl Crow": "sheryl_crow_discog.json", 
  "Cliff Richard": "cliff_richard_discog.json", 
  "The Kingston Trio": "the_kingston_trio_discog.json", 
  "Neil Diamond": "neil_diamond_discog.json", 
  "Dolly Parton": "dolly_parton_discog.json", 
  "Aerosmith": "aerosmith_discog.json", 
  "Adele": "adele_discog.json", 
  "Motley Crue": "motley_crue_discog.json", 
  "Faith Hill": "faith_hill_discog.json", 
  "Christina Aguilera": "christina_aguilera_discog.json", 
  "T.I.": "t.i._discog.json", 
  "Jefferson Starship": "jefferson_starship_discog.json", 
  "R. Kelly": "r._kelly_discog.json", 
  "En Vogue": "en_vogue_discog.json", 
  "Ne-Yo": "ne-yo_discog.json", 
  "Jason Derulo": "jason_derulo_discog.json", 
  "John Mayer": "john_mayer_discog.json", 
  "Bee Gees": "bee_gees_discog.json", 
  "Billy Joel": "billy_joel_discog.json", 
  "The Supremes": "the_supremes_discog.json", 
  "Bruce Springsteen": "bruce_springsteen_discog.json", 
  "Robert Palmer": "robert_palmer_discog.json", 
  "Don Gibson": "don_gibson_discog.json", 
  "Earth, Wind & Fire": "earth,_wind_&_fire_discog.json", 
  "Billy Currington": "billy_currington_discog.json", 
  "War": "war_discog.json", 
  "Conway Twitty": "conway_twitty_discog.json", 
  "Percy Sledge": "percy_sledge_discog.json", 
  "Nancy Sinatra": "nancy_sinatra_discog.json", 
  "The Hollies": "the_hollies_discog.json", 
  "Train": "train_discog.json", 
  "The Monkees": "the_monkees_discog.json", 
  "The Guess Who": "the_guess_who_discog.json", 
  "Neil Sedaka": "neil_sedaka_discog.json", 
  "REO Speedwagon": "reo_speedwagon_discog.json", 
  "Barry Manilow": "barry_manilow_discog.json", 
  "Electric Light Orchestra": "electric_light_orchestra_discog.json", 
  "Donovan": "donovan_discog.json", 
  "Dierks Bentley": "dierks_bentley_discog.json", 
  "Eric Carmen": "eric_carmen_discog.json", 
  "Ohio Players": "ohio_players_discog.json", 
  "Steve Winwood": "steve_winwood_discog.json", 
  "Van Halen": "van_halen_discog.json", 
  "Frank Sinatra": "frank_sinatra_discog.json", 
  "Roger Miller": "roger_miller_discog.json", 
  "Celine Dion": "celine_dion_discog.json", 
  "Lobo": "lobo_discog.json", 
  "Jonas Brothers": "jonas_brothers_discog.json", 
  "Survivor": "survivor_discog.json", 
  "Brenda Lee": "brenda_lee_discog.json", 
  "Whitney Houston": "whitney_houston_discog.json", 
  "Demi Lovato": "demi_lovato_discog.json", 
  "Miley Cyrus": "miley_cyrus_discog.json", 
  "Dixie Chicks": "dixie_chicks_discog.json", 
  "Jennifer Lopez": "jennifer_lopez_discog.json", 
  "Paul Anka": "paul_anka_discog.json", 
  "Ray Stevens": "ray_stevens_discog.json", 
  "Linkin Park": "linkin_park_discog.json", 
  "Van Morrison": "van_morrison_discog.json", 
  "Janet Jackson": "janet_jackson_discog.json", 
  "Dean Martin": "dean_martin_discog.json", 
  "The Kinks": "the_kinks_discog.json", 
  "Jason Aldean": "jason_aldean_discog.json", 
  "Herman's Hermits": "hermans_hermits_discog.json", 
  "Toby Keith": "toby_keith_discog.json", 
  "Mary J. Blige": "mary_j._blige_discog.json", 
  "Pink": "pink_discog.json", 
  "Richard Marx": "richard_marx_discog.json", 
  "Alicia Keys": "alicia_keys_discog.json", 
  "Paul McCartney": "paul_mccartney_discog.json", 
  "Miranda Lambert": "miranda_lambert_discog.json", 
  "Tony Bennett": "tony_bennett_discog.json", 
  "Destiny's Child": "destinys_child_discog.json", 
  "Three Dog Night": "three_dog_night_discog.json", 
  "Barry White": "barry_white_discog.json", 
  "Lady Antebellum": "lady_antebellum_discog.json", 
  "Otis Redding": "otis_redding_discog.json", 
  "The Steve Miller Band": "the_steve_miller_band_discog.json", 
  "Lionel Richie": "lionel_richie_discog.json", 
  "Chris Young": "chris_young_discog.json", 
  "Drake": "drake_discog.json", 
  "Heart": "heart_discog.json", 
  "The Rolling Stones": "the_rolling_stones_discog.json", 
  "Luther Vandross": "luther_vandross_discog.json", 
  "The Byrds": "the_byrds_discog.json", 
  "Prince": "prince_discog.json", 
  "Lil Wayne": "lil_wayne_discog.json", 
  "Trey Songz": "trey_songz_discog.json", 
  "Gloria Estefan": "gloria_estefan_discog.json", 
  "Foreigner": "foreigner_discog.json", 
  "U2": "u2_discog.json", 
  "Joe Nichols": "joe_nichols_discog.json", 
  "Bryan Adams": "bryan_adams_discog.json", 
  "Bonnie Raitt": "bonnie_raitt_discog.json", 
  "Rascal Flatts": "rascal_flatts_discog.json", 
  "OneRepublic": "onerepublic_discog.json", 
  "Grand Funk Railroad": "grand_funk_railroad_discog.json", 
  "Led Zeppelin": "led_zeppelin_discog.json", 
  "Duran Duran": "duran_duran_discog.json", 
  "Air Supply": "air_supply_discog.json", 
  "Ed Sheeran": "ed_sheeran_discog.json", 
  "Tom Jones": "tom_jones_discog.json", 
  "Maroon 5": "maroon_5_discog.json", 
  "Trace Adkins": "trace_adkins_discog.json", 
  "Lonestar": "lonestar_discog.json", 
  "Lenny Kravitz": "lenny_kravitz_discog.json", 
  "The Who": "the_who_discog.json", 
  "Kenny Loggins": "kenny_loggins_discog.json", 
  "Poison": "poison_discog.json", 
  "Poco": "poco_discog.json", 
  "Paul Simon": "paul_simon_discog.json", 
  "Smokey Robinson": "smokey_robinson_discog.json", 
  "Ray Charles": "ray_charles_discog.json", 
  "Billy Squier": "billy_squier_discog.json", 
  "Dr. Hook": "dr._hook_discog.json", 
  "Eddie Money": "eddie_money_discog.json", 
  "Bread": "bread_discog.json", 
  "3 Doors Down": "3_doors_down_discog.json", 
  "Dan Fogelberg": "dan_fogelberg_discog.json", 
  "Chuck Berry": "chuck_berry_discog.json", 
  "The O'Jays": "the_ojays_discog.json", 
  "Cher": "cher_discog.json", 
  "Stevie Wonder": "stevie_wonder_discog.json", 
  "The Drifters": "the_drifters_discog.json", 
  "Martina McBride": "martina_mcbride_discog.json", 
  "The Cars": "the_cars_discog.json", 
  "B.J. Thomas": "b.j._thomas_discog.json", 
  "KC And The Sunshine Band": "kc_and_the_sunshine_band_discog.json", 
  "The Chi-lites": "the_chi-lites_discog.json", 
  "Vanessa Williams": "vanessa_williams_discog.json", 
  "Steely Dan": "steely_dan_discog.json", 
  "Donna Summer": "donna_summer_discog.json", 
  "LeAnn Rimes": "leann_rimes_discog.json", 
  "Sheena Easton": "sheena_easton_discog.json", 
  "The Doors": "the_doors_discog.json", 
  "Bruno Mars": "bruno_mars_discog.json", 
  "Jackson 5": "jackson_5_discog.json", 
  "Blake Shelton": "blake_shelton_discog.json", 
  "Justin Bieber": "justin_bieber_discog.json", 
  "Fleetwood Mac": "fleetwood_mac_discog.json", 
  "The Association": "the_association_discog.json", 
  "ABBA": "abba_discog.json", 
  "Lady Gaga": "lady_gaga_discog.json", 
  "Future": "future_discog.json", 
  "Def Leppard": "def_leppard_discog.json", 
  "George Benson": "george_benson_discog.json", 
  "Carrie Underwood": "carrie_underwood_discog.json", 
  "Styx": "styx_discog.json", 
  "Jay-Z": "jay-z_discog.json"
};
export default DATA;